### PR TITLE
Amani-Zen-Theme: Made changes for ticket 1094 for menu item dropdowns on hover

### PR DESCRIPTION
**Pull request by erica-scott**
Added new module menu_expanded for easier maneuvering of the expanded functionality. Exported changes so that main menu is working properly now. This is related to issue https://github.com/PeaceGeeksSociety/amani/issues/1094

### CODE REVIEW

**Comment by PeaceGeeksProjects** [comment]
@bensinjin could you please verify and push to the sites.

**Comment by bensinjin** [comment]
Does this work on mobile?

**Comment by PeaceGeeksProjects** [comment]
@bensinjin I don't think there is 'hovering' on mobile :)  you have to click on a menu item then the sub-menu appear

**Comment by bensinjin** [comment]
Right, but does that click work?

**Comment by PeaceGeeksProjects** [comment]
yes it does on my iPhone

**Pull request merged**
